### ISSUE TITLE
The plug-in gives error with text in Chinese when processing text with Python

### ISSUE THREAD

**Issue by SN-CH** [npp-plugins/pork2sausage#14]
I installed Pork2sausage plug-in and decided to check how it goes along with Python. So, I created the following pork2sausage.ini file:
[Python]
progPath=C:\Users\Sergey\AppData\Local\Programs\Python\Python39\python.exe
progCmd=python $(SELECTION)
workDir=C:\Users\Sergey\AppData\Local\Programs\Python\Python39\

Should I select 3+2 and give command to make the sausage, I have got error message with text in Chinese, depicted at the screen-shot.

![Screen-shot_2021-03-19_17-32-46](https://user-images.githubusercontent.com/42577865/111797899-9c368980-88da-11eb-8fc6-9e7066b76430.png)

I would appreciate some one telling me what is wrong with my ini-file (really, I have no clue about it, everything seems to be correct) and what this message means.

@donho You may want to consider replacing the Chinese text with its English equivalent. And the last, but not the least, thank you very much for great text editor.

**Comment by dinkumoil** [comment]
@SN-CH 

The reason for this issue is that the error output routine of the plugin is not Unicode aware. I filed  PR #11 some **years** ago but it is still in the pipeline, unnoticed by @donho .

If you want to use a fixed version (that also fixes another bug, see the comments to my PR mentioned above) you can go to the repo of [my fork of this plugin](https://github.com/dinkumoil/pork2sausage).
